  datadog:
    image: gcr.io/datadoghq/agent:7
    container_name: datadog
    env_file: .env
    environment:
      DD_SITE: ${DD_SITE}
      DD_API_KEY: ${DD_API_KEY}
      DD_ENV: dev

      # APM + DogStatsD
      DD_APM_ENABLED: "true"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"

      # (NEW) Optional: add global tags so even untagged metrics carry env/service
      DD_DOGSTATSD_TAGS: "env:dev,service:elixir-metrics"

      # 🔵 LOGS
      DD_LOGS_ENABLED: "true"
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
      DD_CONTAINER_EXCLUDE: "name:datadog"

      # (optional) accept OTLP directly
      DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT: "0.0.0.0:4317"
      DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT:  "0.0.0.0:4318"